Component
Studeal/sqldashboard pull request #2
Opened 2017-01-30 15:52 UTC by hide06

Design page create/edit component.

2017-01-30 15:53 UTC, hide06 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create / Edit Component](https://trello.com/c/dhxWh3CJ/16-create-edit-component)

2017-01-31 13:50 UTC, qdequippe requested changes
Add vendors and web in .gitignore

2017-01-31 13:50 UTC, qdequippe commented on app/Resources/views/base.html.twig
> +<!DOCTYPE html>
If this file is not required you can delete it

2017-01-31 13:50 UTC, qdequippe commented on app/Resources/views/default/index.html.twig
> +{% extends 'base.html.twig' %}
If this file is not required you can delete it

2017-01-31 13:50 UTC, qdequippe commented on composer.json
> +    "name": "ashleyberthon/studealproject",
Put `studeal/sqldashboard` here :)

2017-01-31 13:50 UTC, qdequippe commented on src/AppBundle/Controller/AppController.php
> +
Don't hesitate to add some PHP doc here and in the class

2017-01-31 13:50 UTC, qdequippe commented on src/AppBundle/Resources/config/routing.yml
> +    path:     /add_component
if you can, update the routing like `/components/add` and `/components/{componentId}/edit` (the last one will be useful after)

2017-01-31 13:50 UTC, qdequippe commented on src/AppBundle/Resources/views/App/component.html.twig
> +{% extends "AppBundle::layout.html.twig" %}
It will be better to split the left panel from the rest. For example a `sidebar.html.twig`

2017-01-31 13:50 UTC, qdequippe commented on src/AppBundle/Resources/views/App/component.html.twig
> +{% block stylesheets %}
Put this at the beginning of the file

2017-01-31 15:06 UTC, qdequippe commented on composer.json
> +    "name": "studeal/studealproject",
studeal/sqldashboard

2017-01-31 15:09 UTC, qdequippe reviewed
Add web/assets/vendor to .gitignore

2017-02-01 09:26 UTC, qdequippe requested changes

2017-02-01 09:26 UTC, qdequippe commented on .bowerrc
> +{
Bootstrap CDN used so this file is used now?

2017-02-01 09:26 UTC, qdequippe commented on composer.json
> +    "license": "proprietary",
Set an open source license here

2017-02-01 09:46 UTC, qdequippe approved these changes

2017-02-01 10:33 UTC, merged