Dashboard
Studeal/sqldashboard pull request #3
Opened 2017-01-30 15:52 UTC by tinkerbell00

Dashboard design 
Charts position;
Charts dimensions;
Edit dashboard/components menu;
Share dashboard page;

2017-01-30 15:54 UTC, tinkerbell00 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard](https://trello.com/c/bG0fWEbg/15-dashboard)

2017-01-31 13:57 UTC, qdequippe commented
I have an Exception when I try to access / (http://127.0.0.1:8000/)

```
An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "app_add_component" as such route does not exist.").
```
Do you have the same exception?

2017-01-31 15:47 UTC, qdequippe requested changes
`web/assets/vendor` to add to .gitignore

2017-01-31 15:47 UTC, qdequippe commented on src/AppBundle/Resources/views/App/dashboard.html.twig
> +                                                    class="fa fa-usd"
The dropdown goes out of the page

2017-01-31 16:08 UTC, tinkerbell00 commented on src/AppBundle/Resources/views/App/dashboard.html.twig
> +                                                    class="fa fa-usd"
Dropdown fixed

2017-01-31 16:39 UTC, qdequippe commented
too many files in this PR, maybe check gitignore file

2017-02-01 10:55 UTC, qdequippe approved these changes

2017-02-01 12:21 UTC, merged