Profile Admin/General User
Studeal/sqldashboard pull request #4
Opened 2017-01-30 15:58 UTC by whatzerrname

Design Profile Admin/General User

2017-01-30 16:00 UTC, whatzerrname commented
Design Profile Admin/General User

2017-01-30 16:02 UTC, whatzerrname commented
![](https://github.trello.services/images/mini-trello-icon.png) [Admin - User profil](https://trello.com/c/m2o0T9Lr/14-admin-user-profil)

2017-01-31 14:06 UTC, qdequippe requested changes

2017-01-31 14:06 UTC, qdequippe commented on .idea/copyright/profiles_settings.xml
> +<component name="CopyrightManager">
Add it to .gitignore

2017-01-31 14:06 UTC, qdequippe commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Add it to .gitignore

2017-01-31 14:06 UTC, qdequippe commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Add it to .gitignore

2017-01-31 14:06 UTC, qdequippe commented on .idea/sqldashboard.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Add .idea folder to .gitignore

2017-01-31 14:06 UTC, qdequippe commented on src/AppBundle/Resources/views/App/pagination.html.twig
> +{#
Think about https://github.com/KnpLabs/KnpPaginatorBundle maybe later

2017-01-31 14:06 UTC, qdequippe commented on src/AppBundle/Resources/views/App/userProfile.html.twig
> +        <title>{% block title %}Profile Admin{% endblock %}</title>
why do you need to include all headers to update the title and/or css check https://github.com/Studeal/sqldashboard/pull/2/files

2017-01-31 14:06 UTC, qdequippe commented on web/assets/css/style.css
> +* {
maybe put this in user.css

2017-01-31 14:14 UTC, whatzerrname commented on src/AppBundle/Resources/views/App/userProfile.html.twig
> +        <title>{% block title %}Profile Admin{% endblock %}</title>
Bien vu 🙈

2017-01-31 14:24 UTC, whatzerrname reviewed
Review:
- .idea added to .gitignore
- OK for deletion of index.html.twig
- KNP Pagination on to do list
- OK to remove redundant stylesheet links on UserProfile
- Created user.css

2017-01-31 15:03 UTC, qdequippe commented on .idea/copyright/profiles_settings.xml
> +<component name="CopyrightManager">
@whatzerrname we have to resolve conflicts on .gitignore above maybe to remove this file

2017-01-31 15:03 UTC, qdequippe commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
@whatzerrname we have to resolve conflicts on .gitignore above maybe to remove this file

2017-01-31 15:03 UTC, qdequippe commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
@whatzerrname we have to resolve conflicts on .gitignore above maybe to remove this file

2017-01-31 15:03 UTC, qdequippe commented on .idea/sqldashboard.iml
> +<?xml version="1.0" encoding="UTF-8"?>
@whatzerrname we have to resolve conflicts on .gitignore above maybe to remove this file

2017-01-31 15:38 UTC, whatzerrname commented on .idea/copyright/profiles_settings.xml
> +<component name="CopyrightManager">
Est-ce que c'est bon maintenant? @qdequippe

2017-01-31 15:48 UTC, qdequippe requested changes
.idea folder is still present. You need to remove it

2017-01-31 16:07 UTC, qdequippe approved these changes

2017-01-31 16:10 UTC, merged